# used for development
version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # volumes:
    #   - ./server:/home/server/app
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - 'postgres_db'
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - ./zpostgres-data:/var/lib/postgresql/data
# mount go directory to pc
# live reload for go
# consider using docker for next.js
# consider putting GO_ENV in docker-compose file and maybe deleting Dockerfile.dev
