# used for development
version: '3.8'
services:
  server:
    build: ./server
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - 'postgres_db'
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - ./zpostgres-data:/var/lib/postgresql/data
# go docker needs live reload
# consider using docker for front-end
