version: '3.8'
services:
  server:
    build: ./server
    restart: always
    ports:
      - '5000:5000'
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - ./zpostgres-data:/var/lib/postgresql/data
# go docker api cant connect to database
# go docker needs live reload
# make dev command to start react and docker containers
