version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    depends_on:
      - 'server'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    depends_on:
      - 'postgres'
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - zpostgres-data:/var/lib/postgresql/data
volumes:
  zpostgres-data:
    driver_opts:
      device: './server/zpostgres-data'
# for some reason the server doesn't restart automatically when it crashes. The problem is with the Watcher live reload package.