FROM golang:alpine3.15

WORKDIR /app

ENV GO_ENV=development

# installs package for live reload
RUN go install github.com/canthefason/go-watcher/cmd/watcher@latest

# starts live reload
CMD ["/go/bin/watcher"]